### ISSUE TITLE
Is This Real 

### ISSUE THREAD

**Issue by Shikhar2929** [shuoros/cifar100-resnet50-pytorch#1]
### This is groundbreaking stuff- why is this not published in a paper? The state-of-the-art model on papers with code is 96%, whereas you have gotten 98+%. Did you train on both the training and testing? 
Congratulations on the results- this is really good stuff if it is legitimate.

**Comment by grey1989** [comment]
i think too

**Comment by shuoros** [comment]
Answered in #2.
